[server]
# Basic server settings for Streamlit Cloud
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
# Don't automatically open browser on cloud
gatherUsageStats = false

[theme]
# Simple theme settings
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
